---
services:
  scriberr:
    # image: ghcr.io/rishikanthc/scriberr:nightly
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
      pocketbase:
        condition: service_started

    ports:
      - "3000:3000"
      - "9243:9243" # Optionally expose JobQueue UI
    environment:
      - OPENAI_API_KEY=<reallylongsecretkey>
      - OPENAI_ENDPOINT=http://ollama:11434/v1
      - OPENAI_MODEL=llama3.2 # Ensure this model matches in `ollama-models` service
      - OPENAI_ROLE=user
      - POCKETBASE_ADMIN_EMAIL=admin@example.com
      - POCKETBASE_ADMIN_PASSWORD=1234567890
      - POCKETBASE_URL=http://pocketbase:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SCRIBO_FILES=/scriberr
      - DEV_MODE=false
      - CONCURRENCY=1
    volumes:
      - ./scriberr/pb_data:/app/db
      - ./scriberr:/scriberr
      - ./scriberr/models:/models

  redis:
    image: redis:7-alpine
    volumes:
      - ./.dockerdata/redis:/data

  pocketbase:
    image: ghcr.io/rishikanthc/pocketbase:22.22
    environment:
      - POCKETBASE_ADMIN_EMAIL=admin@example.com  # Replace with your admin email
      - POCKETBASE_ADMIN_PASSWORD=1234567890  # Replace with your admin password
    ports:
      - "8080:8080"  # Expose PocketBase on port 8080
    volumes:
      - ./pb_data:/pb/pb_data  # Mount the PocketBase data directory for persistence
    restart: unless-stopped  # Always restart unless explicitly stopped


